### ISSUE TITLE
Ready event after connecting to an active event

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-service#191]
With the old versions of puppet-service, ```start()``` method is called every time when puppet-service connect to a puppet-server, and the puppet can check with ```this.state.on()``` to decide whether it's the initial start call or following ups. So that we can check if data is loaded to emit a 'ready' event. (puppet service will emit a login event when connecting to a ON puppet).

https://github.com/huan/state-switch/blob/1b14e623226e5e901db58313aa6aa4495aeefbbf/src/service-ctl/service-ctl.ts#L52-L57
But now, ```onStart()``` will not be called, I think puppet-service should check the state of puppet data and decide whether to emit a Ready event or not.

- [x] add a new property in wechaty-puppet marking puppet's ready status. I'm thinking doing so in the login mixin. https://github.com/wechaty/puppet/pull/179
- [x] add a checker in puppet-service event-stream-manager module to emit a ready event if puppet is ready. https://github.com/wechaty/puppet-service/pull/192

I'll updated this post and link corresponding PR.

**Comment by huan** [comment]
A Pull Request to demonstrate your proposal is welcome.

**Comment by hcfw007** [comment]
Is there already a property in puppet to get the Ready state of data or a method to get such state? Because this might includes changes to other packages like puppet.

**Comment by huan** [comment]
I don't think we have any property in puppet to store the ready state for now.

I can think of two ways to solve it:

1. add a ready flag variable in the puppet system, so that others will always be able to know whether a puppet is ready, like `puppet.isLoggedIn`:

https://github.com/wechaty/puppet-service/blob/1e4721f0a53c4b3453cf61cf72ea0113d93494f9/src/server/event-stream-manager.ts#L84-L91

2. Add a variable in the Puppet Service Server, so that you can store the ready state for future usage. Related source code might be useful:

https://github.com/wechaty/puppet-service/blob/1e4721f0a53c4b3453cf61cf72ea0113d93494f9/src/server/event-stream-manager.ts#L214-L219

**Comment by hcfw007** [comment]
I like the first option.
Ready flag might be useful since the bot may want to know if the puppet data is ready. On ready listener is not enough, because you might want to know if the contact data is loaded when trying to forward a message.
And it won't change to not ready when running so a property is good enough, no need to be a function to get the state.

I'll work on that if you are with me.

**Comment by hcfw007** [comment]
OK. Here's what I'm gonna do.

- [ ] add a new property in wechaty-puppet marking puppet's ready status. I'm thinking doing so in the login mixin.
- [ ] add a checker in puppet-service event-stream-manager module to emit a ready event if puppet is ready.

I'll updated this post and link corresponding PR.

**Comment by hcfw007** [comment]
Mission accomplished, Cheers.
