### ISSUE TITLE
Paimon plan to support wechaty1.x.

### ISSUE THREAD

**Issue by zpaimon** [wechaty/puppet-service#193]
Paimon plan to support wechaty1.x.

**Comment by huan** [comment]
It's great to know that the Paimon start planning to support the wechaty v1.x!

As we have an upgrading and certification program for Wechaty Puppet Service (PWS) for the Wechaty ecosystem beta stage, please read the program details at

- https://github.com/wechaty/puppet-service/issues/194

And let me know if you have any questions/feedback.

My suggestion for you is to follow the application template and post your application under this issue, and then I can start helping you to roll in the Wechaty Puppet Service Certification Program.

Thank you very much.

**Comment by zpaimon** [comment]
Wechaty Puppet Service (WPS) Certification Application

1. What's your WPS Server Name Indication (SNI)?

paimon


2. What Level are you going to apply for? (the minimum level that can be applied is Level-2, and the higher the better)
level-2
3. Please copy/paste the Level-N requirements below, and comment on every requirement to explain why you are qualified:
https://wechaty.js.org/docs/puppet-services/paimon

4. You understand and agree that the right of final interpretation of the Terms of Service of the Wechaty ecosystem resides with the Wechaty community.  (Y/N)
Y
4. Your name (sign)
ZPAIMON

**Comment by huan** [comment]
Dear @zpaimon ,

Thank you very much for sending the application to the Wechaty community for certificating the Paimon Wechaty Puppet Service (WPS)!

I have read you are applying the `Level-2`. However, you have not answered question No. 3 correctly: it should list all the `Level-2` requirements and mark them one by one to make sure you will fulfill them, instead of providing the wechaty official website link.

Here I have listed all the `Level-1` to `Level-4` requirements for you:

```md
- Level-1: a Level-0 WPS that meets the following requirements:
    - [ ] secured by the TLS. (CA will be signed by the Wechaty community, with a $100 per month CA management fee)
- Level-2: a Level-1 WPS that meets the following requirements:
    - [ ] published the WPS landing page at Wechaty's official website under the `https://wechaty.js.org/docs/puppet-service/${SNI}`
    - [ ] published the WPS official website, and link it to the landing page, for users to apply, pay, and manage their WPS tokens
    - [ ] published a Term-of-Service page and linked its URL to the WPS landing page
    - [ ] published a Privacy-Policy page and linked its URL to the WPS landing page
    - [ ] published at least one support channel on the landing page
    - [ ] watched the https://github.com/wechaty/puppet-supports/issues for related support requests.
    - [ ] published at least one blog post on wechaty.js.org to announce the WPS, and link the blog posts to the landing page
    - [ ] agreed to maintain the WPS landing page on the Wechaty website when there are any updates needed
- Level-3: a Level-2 WPS that meets the following requirements:
    - [ ] agree to provide at least 2 non-expiring free tokens for each developer who has joined the Wechaty Developers Program
    - [ ] agree to provide at least 20 non-expiring free tokens to the Wechaty community.
- Level-4: a Level-3 WPS that meets the following requirements:
    - [ ] support the Wechaty open-source project by donating more to the Wechaty community via OpenCollective
```

Please copy & paste the above markdown, and mark them one by one to confirm that you can meet them in the following 30 days. The application will be processed in 3 steps:

1. After we have received your confirmation, then we will be able to issue a CA to you immediately, with a 30 days alpha period. 
2. After we have confirmed all the requirements are met (published online, and confirmed by email), we will send an updated CA to you with a 3 months beta period; 
3. After 2 months, if everything is good, then we will issue a 12 monthly validation CA for production, and we will keep updating the CA once per year.

I saw you have applied the `Level-2` in the previous reply, it is absolutely fine. However, I strongly suggest that you consider the higher level (for example, `Level-3`) because you can support the community more by providing the free tokens to the Wechaty contributors, and the more contributors will use Paimon, the more feedback you will get back from the community.

Thank you very much, and I hope we can enable TLS on paimon PWS soon!
